name: Run Pester Tests

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  pester:
    runs-on: windows-latest 

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Install Pester
      shell: pwsh
      run: Install-Module -Name Pester -Force -Scope CurrentUser

    - name: Run Pester Tests
      working-directory: ./src 
      run: |
        # Run Pester tests with Code Coverage
        $config = New-PesterConfiguration
        $config.Run.Path = "."
        $config.CodeCoverage.Enabled = $true
        $config.TestResult.Enabled = $true
        Invoke-Pester -Configuration $config

    - name: Upload code coverage report
      if: ${{ success() }}
      uses: actions/upload-artifact@v2
      with:
        name: code-coverage-report
        path: src\coverage.xml
